# Generated by Django 3.0.3 on 2020-08-23 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('trainrakecoach_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('coach_no', models.IntegerField()),
                ('prefix', models.CharField(max_length=10)),
                ('coach_type', models.CharField(max_length=264)),
                ('coach_class', models.CharField(max_length=264)),
                ('description', models.CharField(max_length=264)),
                ('position', models.IntegerField()),
                ('coach_name', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_no', models.IntegerField(primary_key=True, serialize=False)),
                ('train_name', models.CharField(max_length=264)),
                ('description', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Rake',
            fields=[
                ('trainrake_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('rake_no', models.IntegerField()),
                ('description', models.CharField(max_length=264)),
                ('status', models.CharField(max_length=20)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rakes', to='wspd_app.Train')),
            ],
        ),
        migrations.CreateModel(
            name='FaultTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wsp_status_code', models.IntegerField(default=0)),
                ('fault_datetime', models.DateTimeField()),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faults', to='wspd_app.Coach')),
            ],
        ),
        migrations.AddField(
            model_name='coach',
            name='rake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='wspd_app.Rake'),
        ),
    ]
